// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJ31HS3OD8dKItrpDMDbnJbzeB-HJEgI',
    appId: '1:538115197279:web:9f2b6c680d41d3331a0eea',
    messagingSenderId: '538115197279',
    projectId: 'notes-2024',
    authDomain: 'notes-2024.firebaseapp.com',
    storageBucket: 'notes-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aCI7t4QF0XIkZ4542aeklFIrCe1vrYc',
    appId: '1:538115197279:android:442f31b9b3a7e1211a0eea',
    messagingSenderId: '538115197279',
    projectId: 'notes-2024',
    storageBucket: 'notes-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS6CHQsLTuGCZCvUTlyDhJbXAqt0b3kT0',
    appId: '1:538115197279:ios:c6ee9a237e512c4e1a0eea',
    messagingSenderId: '538115197279',
    projectId: 'notes-2024',
    storageBucket: 'notes-2024.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS6CHQsLTuGCZCvUTlyDhJbXAqt0b3kT0',
    appId: '1:538115197279:ios:c6ee9a237e512c4e1a0eea',
    messagingSenderId: '538115197279',
    projectId: 'notes-2024',
    storageBucket: 'notes-2024.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwJ31HS3OD8dKItrpDMDbnJbzeB-HJEgI',
    appId: '1:538115197279:web:90e7b126a43779821a0eea',
    messagingSenderId: '538115197279',
    projectId: 'notes-2024',
    authDomain: 'notes-2024.firebaseapp.com',
    storageBucket: 'notes-2024.appspot.com',
  );
}
